# Generated by Django 5.0.6 on 2024-07-08 08:20

import datetime
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='course_categories')),
            ],
            options={
                'verbose_name': 'نوع  كورس',
                'verbose_name_plural': 'انواع الكورسات',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('created_in', models.DateField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم المتحدث')),
                ('name_en', models.CharField(max_length=255, verbose_name='name in english')),
                ('photo_banner', models.ImageField(blank=True, null=True, upload_to='speakers_photos')),
                ('personal_photo', models.ImageField(blank=True, null=True, upload_to='speakers_photos')),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_ar', models.TextField(blank=True, null=True)),
                ('short_bio_en', models.TextField(blank=True, null=True)),
                ('short_bio_ar', models.TextField(blank=True, null=True)),
                ('instgram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShopsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='workshopscategory_banner')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='courses_banner_general', verbose_name='thumbnail')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم كورس')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم الكورس انجليزي')),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='وصف بالعربي')),
                ('price', models.FloatField(default=0)),
                ('isonsale', models.BooleanField(default=False)),
                ('onsale', models.FloatField(default=0)),
                ('trailer', models.FileField(blank=True, help_text='Allowed : "mp4", "webm", "avi", "AVI", "WebM" ', null=True, upload_to='course_trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi', 'AVI', 'WebM'])], verbose_name='الفيديو')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursecategory')),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'كورسات',
            },
        ),
        migrations.CreateModel(
            name='Ep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='courses_banner', verbose_name='thumbnail')),
                ('video', models.FileField(help_text='Allowed : "mp4", "webm", "avi", "AVI", "WebM" ', upload_to='course', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi', 'AVI', 'WebM'])], verbose_name='الفيديو')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الحلقة عربي')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم الحلقة انجليزي')),
                ('descr_en', models.TextField(blank=True, null=True, verbose_name='description ')),
                ('descr_ar', models.TextField(blank=True, null=True, verbose_name='وصف ')),
                ('created_in', models.DateField(default=datetime.datetime.now, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم المدرس')),
                ('name_en', models.CharField(max_length=255, verbose_name='name in english')),
                ('photo_banner', models.ImageField(blank=True, null=True, upload_to='instructors_photos')),
                ('time_added', models.DateField(default=datetime.datetime.now, editable=False)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_ar', models.TextField(blank=True, null=True)),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coursecategory')),
            ],
            options={
                'verbose_name': 'المدرس',
                'verbose_name_plural': 'المدرسين',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor', verbose_name='المدرس'),
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='meetups_banner')),
                ('meetupname_en', models.CharField(max_length=255)),
                ('meetupname_ar', models.CharField(max_length=255)),
                ('time_added', models.DateField(default=datetime.datetime.now)),
                ('time_event_starts_in', models.DateField(default=datetime.datetime.now)),
                ('is_finished', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('isonsale', models.BooleanField(default=False)),
                ('onsale', models.FloatField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='وصف بالعربي')),
                ('insctructors', models.ManyToManyField(to='core.instructor')),
            ],
            options={
                'verbose_name': 'Meetup',
                'verbose_name_plural': 'Meetups',
            },
        ),
        migrations.CreateModel(
            name='MeetupTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('howmany', models.IntegerField(default=0)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meetup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meetup Ticket',
                'verbose_name_plural': 'MeetupTickets',
            },
        ),
        migrations.CreateModel(
            name='Summit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='summits_banner')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم المؤتمر')),
                ('name_en', models.CharField(max_length=255, verbose_name='name in english')),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('isonsale', models.BooleanField(default=False)),
                ('onsale', models.FloatField(default=0)),
                ('time_added', models.DateField(default=datetime.datetime.now)),
                ('time_event_starts_in', models.DateField(default=datetime.datetime.now)),
                ('is_finished', models.BooleanField(default=False)),
                ('trailer', models.FileField(blank=True, help_text='Allowed : "mp4", "webm", "avi", "AVI", "WebM" ', null=True, upload_to='summit_trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi', 'AVI', 'WebM'])], verbose_name='الفيديو')),
                ('Speakers', models.ManyToManyField(blank=True, to='core.speakers')),
            ],
            options={
                'verbose_name': 'Summit',
                'verbose_name_plural': 'Summits',
            },
        ),
        migrations.CreateModel(
            name='SummitTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('summit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.summit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QrcodeForTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('summitticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.summitticket')),
            ],
            options={
                'verbose_name': 'SummitTicket',
                'verbose_name_plural': 'SummitTickets',
            },
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserCourses',
                'verbose_name_plural': 'UserCourses',
            },
        ),
        migrations.CreateModel(
            name='WorkShops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workshopscategory')),
            ],
            options={
                'verbose_name': 'Workshops',
                'verbose_name_plural': 'Workshops',
            },
        ),
    ]
