# Generated by Django 5.0.6 on 2024-07-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitticket',
            name='did_he_pay',
            field=models.BooleanField(default=False),
        ),
    ]
