# Generated by Django 5.0.6 on 2024-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_summitticket_sended_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='summitticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('V', 'VIP'), ('S', 'Standard')], max_length=255, null=True),
        ),
    ]
